/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTO.PedidoDTO;
import Negocio.Control;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author uirtis
 */
public class ModificarPedido extends javax.swing.JFrame {
    PedidoDTO ped, nuevoPed;
    Control control;
    private Map<String, Integer> cambiosAlimentos = new HashMap<>();
    /**
     * Creates new form crearPedido
     */
    public ModificarPedido(PedidoDTO ped) {
        initComponents();
        this.ped=ped;
        nuevoPed=new PedidoDTO();
        control=new Control();
        llenarCombo();
        txtCantidad.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e){
                char c= e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAlimento = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        agregarPedido = new javax.swing.JButton();
        cancelarPedido = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminarAlimento = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 2, 24)); // NOI18N
        jLabel2.setText("Modificar Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setText("Alimento");

        jLabel3.setText("Cantidad");

        cbAlimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamburguesa", "Pizza", "Ensalada", "Pasta" }));
        cbAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlimentoActionPerformed(evt);
            }
        });

        agregarPedido.setText("Actualizar");
        agregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidoActionPerformed(evt);
            }
        });

        cancelarPedido.setText("Cancelar");
        cancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPedidoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar por completo");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminarAlimento.setText("Eliminar alimento");
        btnEliminarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(agregarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarPedido)))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarAlimento)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnEliminarAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarPedido)
                    .addComponent(cancelarPedido))
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlimentoActionPerformed
        
    }//GEN-LAST:event_cbAlimentoActionPerformed

    private void agregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoActionPerformed
         String alimentoSeleccionado = (String) cbAlimento.getSelectedItem();
        String nuevaCantidadStr = txtCantidad.getText();

        if (alimentoSeleccionado != null && !nuevaCantidadStr.isEmpty()) {
            int nuevaCantidad = Integer.parseInt(nuevaCantidadStr);

            
            cambiosAlimentos.put(alimentoSeleccionado, nuevaCantidad);

            JOptionPane.showMessageDialog(this, "Cambio agregado: " + alimentoSeleccionado + " - " + nuevaCantidad);

            actualizarComboBox();
            txtCantidad.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un alimento y una cantidad válida.");
        }
    }//GEN-LAST:event_agregarPedidoActionPerformed

    private void cancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPedidoActionPerformed
        Pedido frmPedido=new Pedido();
        frmPedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarPedidoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String cadenaAlimentos = ped.getAlimento();
        String[] alimentos = cadenaAlimentos.split(", ");

        StringBuilder nuevaCadena = new StringBuilder();

        Map<String, Integer> alimentosActualizados = new HashMap<>();
       
        for (String alimento : alimentos) {
            String[] partes = alimento.split(" ");
            String nombre = partes[0];

            
            if (cambiosAlimentos.containsKey(nombre)) {
                nuevaCadena.append(nombre).append(" ").append(cambiosAlimentos.get(nombre));
                alimentosActualizados.put(nombre, cambiosAlimentos.get(nombre)); 
            } else {
                nuevaCadena.append(alimento);
            }
            nuevaCadena.append(", "); 
        }

        for (Map.Entry<String, Integer> entry : cambiosAlimentos.entrySet()) {
            String nombre = entry.getKey();
            if (!alimentosActualizados.containsKey(nombre)) {
                nuevaCadena.append(nombre).append(" ").append(entry.getValue()).append(", ");
            }
        }

        
        if (nuevaCadena.length() > 0) {
            nuevaCadena.setLength(nuevaCadena.length() - 2);
        }

        ped.setAlimento(nuevaCadena.toString());
        control.actualizarPedido(ped);
        
        JOptionPane.showMessageDialog(this, "Todos los cambios han sido aplicados.");
        actualizarComboBox();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlimentoActionPerformed
        String alimentoSeleccionado = (String) cbAlimento.getSelectedItem();

        if (alimentoSeleccionado != null) {
           
            String cadenaAlimentos = ped.getAlimento();
            String[] alimentos = cadenaAlimentos.split(", ");

            if (alimentos.length <= 1) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar el único alimento en la lista.");
                return; 
            }

            StringBuilder nuevaCadena = new StringBuilder();

            for (String alimento : alimentos) {
                if (!alimento.startsWith(alimentoSeleccionado + " ")) { 
                    nuevaCadena.append(alimento).append(", ");
                }
            }

            if (nuevaCadena.length() > 0) {
                nuevaCadena.setLength(nuevaCadena.length() - 2);
            }

            ped.setAlimento(nuevaCadena.toString());
            control.actualizarPedido(ped);
            JOptionPane.showMessageDialog(this, "Alimento eliminado con éxito.");
            actualizarComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un alimento para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarAlimentoActionPerformed

    private void llenarCombo(){
        cbAlimento.removeAllItems();
        String[] alimentos = ped.getAlimento().split(", ");
        
        for (String alimento : alimentos) {
            String[] partes = alimento.split(" "); 
            if (partes.length == 2) {
                String nombre = partes[0];
                cbAlimento.addItem(nombre); 
            }
        }
        
        cbAlimento.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
                String alimentoSeleccionado = (String) cbAlimento.getSelectedItem();
                if (alimentoSeleccionado != null) {
                    
                    for (String alimento : alimentos) {
                        String[] partes = alimento.split(" ");
                        if (partes[0].equals(alimentoSeleccionado)) {
                            txtCantidad.setText(partes[1]); 
                            break;
                        }
                    }
                }
            }
        });
        
    }
   
    private void actualizarComboBox() {
        
        String cadenaAlimentos = ped.getAlimento();
        String[] alimentos = cadenaAlimentos.split(", ");

        cbAlimento.removeAllItems();

        for (String alimento : alimentos) {
            cbAlimento.addItem(alimento);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPedido;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminarAlimento;
    private javax.swing.JButton cancelarPedido;
    private javax.swing.JComboBox<String> cbAlimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
